### ISSUE TITLE
Pre-built jar for java client library

### ISSUE THREAD

**Issue by philandstuff** [google/certificate-transparency#1086]
There is a java client library in this repo under the java/ directory. It would be nice to have access to a pre-built jar file to easily depend on it in other projects.

Separately, it'd be good to be able to download the jar from maven central in the same way that you can get packages like guava: http://mvnrepository.com/artifact/com.google.guava/guava

**Comment by alexanderkjall** [comment]
This would make it much easier to use it, it would also be nice if it was possible to build the code with maven.

**Comment by pphaneuf** [comment]
We used to have some pre-built jar files, but it turned out to be rather difficult to maintain for us. Our conclusion was that having jars in the source repository was the wrong approach, and that this would be what things like Maven are designed to solve. Unfortunately, we are lacking the necessary Maven knowledge to do this, but we would welcome contributions in this area?

I will close this issue, but feel free to open one for adding this project to Maven?

**Comment by alexanderkjall** [comment]
I opened a new ticket for that here: https://github.com/google/certificate-transparency/issues/1374

And also made a start on an implementation.
