### ISSUE TITLE
Using of two/three methods not explained.

### ISSUE THREAD

**Issue by stas730** [google/certificate-transparency#1202]
I want to create test CA & Certificate with CT, EV and other trust extensions. Using of two/three methods to implement CT not explained. I can use X509v4 (not a mistake), TLS and OCSP in one certificate?

**Comment by stas730** [comment]
Send reply or close…

**Comment by pphaneuf** [comment]
The TLS and OCSP methods done *outside* the certificate, only the X509 option affects the certificate (you need to use the `add-pre-chain` instead of `add-chain` method).

The X509 method requires the CA to do it, of course, but the other methods allow you to add CT on existing certificates, or if your CA is not providing the CT extension in their certificates.

**Comment by pphaneuf** [comment]
By "add CT on existing certificate", I really mean "use CT with existing certifications that do not have CT in them". Once a certificate is signed, it is not possible to modify it, of course!

**Comment by stas730** [comment]
And how to add X.509 or OCSP in OpenSSL.
I know how to install string (X.509). But how to find string data?
And can I add X.509, then TLS extensions, then OCSP?

**Comment by stas730** [comment]
TLS extension*

**Comment by pphaneuf** [comment]
The data that you need to add is what you get back from CT logs when submitting the certificate (with the CT log `add-chain` or `add-pre-chain` endpoints). I believe in mosts cases it ends up being TLS-encoded (the `ct upload` command will put this data in the file pointed at by its `--ct_server_response_out` flag).

You only need *one* of X509, OCSP, or TLS, you can just use the one you find most convenient.

**Comment by stas730** [comment]
And how to add OCSP response? I need to test all three methods and see browser reactions when two or three method used.

**Comment by stas730** [comment]
I will not add all three methods in normal certificate.
But I have an answer: which method is the best?

**Comment by pphaneuf** [comment]
The answer is disappointing: "it depends". :wink: 

The X509 method is simple to use, but requires CA support (which is not always possible), and also makes the certificates bigger (which can be a problem, or at least add some cost on high traffic websites).

The TLS method requires nothing of the CA (or the certificate), and leaves the certificates unchanged (same size as normal), but needs modifications of the HTTPS server (additional configuration, maybe adding a module, etc). This can be difficult, on some platforms.

The OCSP method, I am not sufficiently familiar with, @eranmes might explain better, but I think it also depends on the OCSP provider providing the CT information (which might not be possible?). I'm not certain if it is as well supported in browsers, either?

**Comment by stas730** [comment]
I think, client code exists in this repo.
I have both CA and OCSP local hosting. This is my testing certificate.
And how to get response file to setup it? Look like TLS extension (first steps) or not?

**Comment by stas730** [comment]
Waiting for reply…

**Comment by pphaneuf** [comment]
I'm not sure of the answer, @eranmes should, but he's gone home. He should be able to answer tomorrow, hopefully.

**Comment by eranmes** [comment]
To send SCTLists via the TLS extension the web server has to be configured as described here:
http://www.certificate-transparency.org/resources-for-site-owners

To send SCTLists in a stapled OCSP response:
(a) the CA that signs the OCSP response must include the SCTList in the OCSP response.
(b) the website has to be configured to serve stapled OCSP responses.

Closing this issue as the questions raised here seem more general questions about use/deployment of Certificate Transparency rather than a particular issue / bug with the existing implementations.

I suggest using the first mailing list mentioned here: http://www.certificate-transparency.org/mailing-lists

**Comment by stas730** [comment]
And how to change response OID?
