### ISSUE TITLE
Can't build in Go 1.5.4

### ISSUE THREAD

**Issue by TamalSaha** [google/certificate-transparency#1274]
Hi,
You documentation says this works with [Go 1.1](https://github.com/google/certificate-transparency/tree/master/go). But because of https://github.com/google/certificate-transparency/commit/20f0f2bd1cdaf0ea5da6f008148e0ce10527aa66, I can't build this is in Go 1.5.4.

Thanks.

**Comment by pphaneuf** [comment]
You're right, we should be updating the documentation, we need Go 1.6 now. Due to the increasingly prevalent use of contexts (and the much improved support for cancellation and timeouts of HTTP requests in general), I'm not sure if this would make sense to support Go 1.5?

Go 1.7 is coming out soon, I didn't want to add anything requiring to be *that* up to date, but I'd say still working with the previous version seems reasonable enough?

**Comment by TamalSaha** [comment]
"I'd say still working with the previous version seems reasonable enough?" - Yes. How about today? :)

**Comment by pphaneuf** [comment]
Hehe, okay, I *am* preempting this a little bit, but 1.7 should be there in less than a month.

It's rather unfortunate, but the while the commit you pointed at is indeed the one that broke the backward compatibility and looks fairly spurious (the previous hardcoded constants were working fine), the real problems come in with 9567a856a3750a951eb843c79bde9ff0d92ec6e2.

It might be possible to use a trick like the following to provide two versions of `fetchAndParse`, a helper, or something like that which would make it work on Go 1.5? We'd certainly accept such a contribution, but since we're steaming ahead with 1.7 already on our development systems, we're unlikely to work on this ourselves.

**Comment by TamalSaha** [comment]
I have vendored this library for now. That solves the build problem for us.
