### ISSUE TITLE
go/x509 build fails on Solaris platform, dependency for Docker port

### ISSUE THREAD

**Issue by amitkris** [google/certificate-transparency#1320]
Hi,

The go/x509 package fails to build for Solaris.
Since go/x509 is a dependency for the Docker project and we're working to port Docker for the Solaris platform [github.com/docker/docker/#23397](https://github.com/docker/docker/pull/23397) it would be great if this could be fixed.

The fix is a one word addition. 
Solaris needs to be added as a platform in the go/x509/root_unix.go filed.
-// +build dragonfly freebsd linux openbsd netbsd
+// +build dragonfly freebsd linux openbsd netbsd solaris

Thanks!

**Comment by AlCutter** [comment]
Hi,

I'm curious to know why you depend on CT's modified x509/asn1 packages as opposed to the golang library versions?

Cheers,
Al

**Comment by amitkris** [comment]
HI @AlCutter 

You mean why does Docker depend on it?
They moved to this somewhere in the Docker v1.12 development cycle. I'm not  aware of what the motivation behind this was. Sorry :(

**Comment by daviddrysdale** [comment]
Looks like Docker pulled in a local copy of `github.com/cloudflare/cfssl` in [early June](https://github.com/docker/docker/commit/44793049ce1ad364720b4be915a92291d1f808c2), and  `certificate-transparency` (as of commit 025a5cab06f6a819c455d9fdc9e2a1b6d0982284) came along as a dependency.  (Docker has updated the CFSSL copy a couple of times since, and has [also updated](https://github.com/docker/docker/commit/39143ef15d6b95acc37f209c8ba5ebc4b3d57c79) `certificate-transparency` to commit 0f6e3d1d1ba4d03fdaab7cd716f36255c2e48341)

The Cloudflare PKI and TLS toolkit ([CFSSL](https://github.com/cloudflare/cfssl)) has its own [local copy](https://github.com/cloudflare/cfssl/tree/master/vendor/github.com/google/certificate-transparency/go) of `certificate-transparency`'s Go code (as of commit 0f6e3d1d1ba4d03fdaab7cd716f36255c2e48341 too), which looks to get used in [`signer/local/local.go`](https://github.com/cloudflare/cfssl/blob/master/signer/local/local.go) to [submit pre-certs to a CT log](https://github.com/cloudflare/cfssl/blob/master/signer/local/local.go#L339-L378).

So I don't *think* that the CT-modified x509/asn1 packages are directly used.
