### ISSUE TITLE
x509/root_stub.go build ignore?

### ISSUE THREAD

**Issue by sbogacz** [google/certificate-transparency#1335]
Hi, I've been trying to get a fork of [cloudflare/cfssl](https://github.com/cloudflare/cfssl) working with the latest version of certificate-transparency, however, the latest version doesn't work with cfssl's cross compilation approach. 

For clarification, the build works locally, but not for alternate targets. Some example error output

>Stderr: # github.com/cloudflare/cfssl/vendor/github.com/google/certificate-transparency/go/x509
vendor/github.com/google/certificate-transparency/go/x509/root_unix.go:21: (*Certificate).systemVerify redeclared in this block
>	previous declaration at vendor/github.com/google/certificate-transparency/go/x509/root_stub.go:9

After looking through the relevant certificate-transparency code, I couldn't see why the root_stub.go would be required, nor why it had the build tags it did. I added 
```
// +build ignore
```

which seemed to fix the issue. 

I'm wondering if I'm missing some reason to maintain the stub file in the x509 fork, and if so, whether the inclusion of the build ignore tag could be included? 

Thanks, 
Steven

PS: I would fork and make the change, but it seems excessive for a potential one-liner.

**Comment by daviddrysdale** [comment]
That seems odd; `x509/root_stub.go` has
```
// +build darwin,!cgo
```
so it should only be built on (Darwin for non-cgo builds).  Does the cfssl build system not respect build tags?  What platform was the build that failed for?

(Also, nothing relevant seems to have changed in `root_unix.go`/`root_stub.go` recently, so I can't see why this would be different now.)

**Comment by sbogacz** [comment]
The cfssl project (which I'm not associated with) uses gox for cross-compilation. I'm as confused as anyone as to why the Darwin, !cgo build tags seem to not be respected, but it could well be an issue stemming from the particular use of gox there. 

I was also wondering if CT was planning on continuing to use the forked versions of x509 and asn1, and if there were any plans to resume using the standard libraryks crypto packages.

**Comment by daviddrysdale** [comment]
Unfortunately, I think we're likely to stay forked for the x509/asn1 code because we have a slight divergence in aims. AIUI the core library is keen to be as strict as practically possible, whereas for certificate transparency we want to be rather laxer, so that CT code can parse/log/examine any certificate that occurs in the wild (potentially even including older certificates).

**Comment by sbogacz** [comment]
Fair enough. 

In terms of root_stub.go though, wouldn't the two functions be satisfied by root_darwin.go and root.go (in the case of darwin & !cgo)? Again, I'm definitely open to the idea that I might be missing something here. While I realize that there haven't been changes to the other build files so as to cause any breaking changes, it doesn't seem like the stub file is  required to build (it seemed to build just fine on my darwin system). Ignoring the file at build time didn't seem to impair either normal compilation using go build, nor the cross compilation targets used in cfssl. 

So, my question is, despite there being no recent changes in the x509 files themselves, is there a demonstrable reason for keeping the _stub in the build?

**Comment by daviddrysdale** [comment]
Although we've forked from the golang `crypto/x509` code, we do try to track/merge any upstream changes, and so we want to minimize gratuitous differences to make the merge easier.

Also, from the information so far this sounds much more like a problem with gox or the CFSSL build system, so dropping a file from this repo sounds like a dubious workaround rather than the right solution.  Have you tried asking the CFSSL folk about it?

**Comment by daviddrysdale** [comment]
(I'm going to close this for now, but we can re-open it if you find out more.)
