### ISSUE TITLE
Use maven to build java code

### ISSUE THREAD

**Issue by alexanderkjall** [google/certificate-transparency#1374]
In order to upload the a jar to maven central it's a good first step to build the project with maven.

**Comment by alexanderkjall** [comment]
I made a start on how the layout needs to be here:
https://github.com/alexanderkjall/certificate-transparency/commit/99d77ef439a83cd8f2fb3d7b34c398960c77a11e

the unit tests doesn't reference the testdata correctly, that remains to be fixed before i make a pull request.

feedback is welcome.

**Comment by codingllama** [comment]
Hi Alexander,

Thanks for the initiative, it's much appreciated. I had a quick look and it seems alright to me. A few remarks are:

* Missing version for `build-helper-maven-plugin`
* Missing `project.build.sourceEncoding`

    ```xml
    <properties>
      <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    ```

* Version 0.1.0 - I'm not sure about which version number to pick. Let's see what @AlCutter thinks. (In principle 0.1.0 is fine, we can always bump it later.)
* `httpclient` updated from `4.3.3` to `4.4.1`. I don't see any problems there, assuming it works, just adding it here for future reference.
* There's a `exec`-goal binding for `no.hackeriet.certParser.Application`. I suppose it's a leftover from some other project?

I'm a bit disappointed that there's no official protoc plugin (ofc, that's not on you either). A quick search pointed me to http://vlkan.com/blog/post/2015/11/27/maven-protobuf/, which seems to be what you followed. That seems alright to me.

Feel free to assign me to the PR if/when you open it.

**Comment by daviddrysdale** [comment]
BTW, I just [dropped](https://github.com/google/certificate-transparency/pull/1373) the dependency on `httpclient`.

**Comment by alexanderkjall** [comment]
Thanks for the feedback. I'm mainly working on a hobby project of my own, that needs to read from CT, that's where the no.hackeriet stuff comes from.

The 0.1.0 version number needs to be changed, I don't have any input on what it should be.

I'll incorporate your feedback and make the unit tests work as a next step, I might need to change how files are opened a bit in the application, I'm not sure yet.

**Comment by pphaneuf** [comment]
By the way, protocol buffers are completely unnecessary for the Java code. I did a series of PRs to remove as much as possible (the commits that mention "POJO", mainly):

https://github.com/google/certificate-transparency/commits/master/java

What's left is mainly the parts that use protocol buffer enums, because I wasn't sufficiently comfortable with Java to be sure that I wasn't affecting the semantics in their case. I was intending to consult with someone with better Java competences than I have to finish it, but as you might have that kind of Java competence, it might be simplest for you to finish what I started, and get rid of the rest of it?

**Comment by codingllama** [comment]
My suggestion would be to just write the pom, without any extraneous changes. We can do other improvements (like removing proto dependencies) after we have it. If we use the proto enums, depending on the protos seems appropriate to me (I haven't seen too much of the code though, so take my opinions with a grain of salt). OTOH, if we think that it would help, let's have separate PRs for it.

**Comment by pphaneuf** [comment]
I specifically made a fork of the CT protocol buffers definitions that were used by the Java code, all in `java/ct.proto` (so that we could modify the original one without breaking Java), and as you can see, there's very little left.

I'd definitely suggest separate PRs, for sure, just suggesting that it might be a small enough PR to send first to get rid of the need for `protoc`, if it makes the others easier.

**Comment by alexanderkjall** [comment]
@daviddrysdale Maybe I'm confused, but those commit's look like they only affect the go part of the  code and not the java part?

**Comment by alexanderkjall** [comment]
@codingllama I can't seem to request a review through github for some reason, but the pull request is here: https://github.com/google/certificate-transparency/pull/1375

**Comment by pphaneuf** [comment]
That has been done, as far as I can tell.

The Java code has now been separated into its own repository, also: https://github.com/google/certificate-transparency-java

I'll close this issue, feel free to open another one there!
