### ISSUE TITLE
Somebody please help me...

### ISSUE THREAD

**Issue by homepc91** [google/certificate-transparency#1423]
Hi, I am using Ubuntu 16.04 for Certificate-Transparency Development when I am running ./prepare_etcd.sh. then i am getting some error How to solve it?....Please help me....

I am using etcd v2.1.3 or latest then i am getting same error

i am getting error :- W1013 07:02:03.298388 528384 etcd.cc:798] Got invalid JSON:**

please see the screenshot
![screen shot 2017-11-18 at 10 43 34 am](https://user-images.githubusercontent.com/25889886/32977192-652c676c-cc4e-11e7-8477-aa195f51f1b6.png)

**Comment by grandamp** [comment]
Folks may have more eyes on [Trillian](https://github.com/google/trillian) at the moment, but,  [this issue](https://github.com/google/certificate-transparency/issues/811) [got invalid json] is somewhat common in the ct-server logs.  Have you started any ct-server instances and tested log functionality using the etcd cluster yet?

**Comment by homepc91** [comment]
thanks brother.......yes all things are fine working but i want to know how to solve this problem...

**Comment by grandamp** [comment]
Personally, I'm still a bit of a rookie, but the issue may be with the more recent (3.0+) versions of etcd.  There are a few closed issues on etcd problems within this repo.  We *do* see a high rate of etcd errors via our ct-server instances (a lot of 404 errors on deletes).  Beyond that, I'm afraid I have no other information to offer.

**Comment by homepc91** [comment]
thanks, can i know that....does Google Trillian is better according to you...?
And what are you using Google Trillian or Certificate Transparency..?

**Comment by AlCutter** [comment]
Firstly, unfortunately this error is a bit of a red-herring, four lines up you can see that `clustertool_main:181` logged *"OK"* - this means the provisioning succeeded.
The invalid JSON error line is unrelated noise and due to a subsequent socket read timeout.

However, as gramdamp has already said, **please consider whether a Trillian based CT log meets your requirements** - Trillian is already used by Google and Cloudflare to run their recent logs, and we're  actively working on it.
